//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/PlayerMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerMap"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""3908e16c-fc18-4c7d-858d-d7390ae547a9"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""2321cf4d-54fa-4fd3-bd33-58b2bcc1dfd9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""45af91e9-d8f9-4694-aadd-7e3a1259922c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sequence"",
                    ""type"": ""Button"",
                    ""id"": ""1211e6f0-8ae5-40a3-981f-d5d68fabc679"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sphere"",
                    ""type"": ""Button"",
                    ""id"": ""fdcf466c-1eca-41a5-947c-81fdb250aef7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""9e5625e6-3b8e-4920-bc2f-bcbd83d18e8b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TakeSound"",
                    ""type"": ""Button"",
                    ""id"": ""c46b7389-5b32-4f3f-9b8e-c604e2c8b778"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Options"",
                    ""type"": ""Button"",
                    ""id"": ""e98d424b-8fd5-474d-94c3-eea197c2c836"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sound1"",
                    ""type"": ""Button"",
                    ""id"": ""53c3a5f4-e559-441f-b195-90b28f7fa6e7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sound2"",
                    ""type"": ""Button"",
                    ""id"": ""faadbb65-65d1-4c25-ad5d-43d5f3054405"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sound3"",
                    ""type"": ""Button"",
                    ""id"": ""a4d2923e-e71e-492a-b082-c14749e7007a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sound4"",
                    ""type"": ""Button"",
                    ""id"": ""cc888563-7662-49e8-a50e-67037cdfc7be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sound5"",
                    ""type"": ""Button"",
                    ""id"": ""9990077c-9328-482d-a39d-b0d43555662c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sound6"",
                    ""type"": ""Button"",
                    ""id"": ""0694df17-3359-4915-b04d-6e919212346f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Diary"",
                    ""type"": ""Button"",
                    ""id"": ""aded6917-f487-478d-b9df-1a54aaf805f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reset"",
                    ""type"": ""Button"",
                    ""id"": ""e65caa2a-ba3b-4e0a-bc8c-e4a08bb7140a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortCut1"",
                    ""type"": ""Button"",
                    ""id"": ""0425a4b4-eb91-4cb2-a3af-d5d66ee0e490"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortCut2"",
                    ""type"": ""Button"",
                    ""id"": ""1f90af5c-ef03-4578-9b0e-16d9ba855398"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortCut3"",
                    ""type"": ""Button"",
                    ""id"": ""2ecd76ee-0c00-463e-a311-cdcd7bd5591e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortCut4"",
                    ""type"": ""Button"",
                    ""id"": ""7678ea22-fdfb-41d5-996d-d94c2bda676f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortCut5"",
                    ""type"": ""Button"",
                    ""id"": ""d9b17623-19ee-4a38-8828-ca91f5e97033"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""9974f091-f627-438f-9036-d8829e2b0458"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""fd0a62cc-6c84-477e-83e8-83c71493add1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a50bf436-c638-4c4d-b621-ced5ed5ecb51"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""886659e0-7f37-416a-9a59-6ab134aa16ee"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0d1d4e9f-adb5-44ea-88cc-3318c66233ee"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""434f8102-f2ae-492c-a737-994c97c13e28"",
                    ""path"": ""<XInputController>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dde439e7-5f1c-483a-9f59-543b85730bb2"",
                    ""path"": ""<XInputController>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""750132a7-6c7e-44b4-ab6d-f9db7f04b9cb"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca812dc3-e648-4432-b64c-c55c164f5b2d"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2de9281-ad9f-4033-a363-dfe2aa4d0202"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sequence"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d57ac36d-21f8-4599-be05-3887709e0217"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sequence"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8361bc82-6e98-4be5-8cc0-a11c4e355cd8"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sphere"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6dcfe860-d4ad-4e52-b8be-3fda8441ba0d"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sphere"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dabdc3ec-9904-45b5-b115-8d761b48e4e2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46e8b46d-03cf-458c-856f-d3334f26c058"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c8ba91d-5541-4be3-8ef1-f6b6aac8c5dc"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeSound"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9cf8477c-5562-4b11-9c2a-fbbde90574d4"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeSound"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3540dc8-1682-4909-8ef4-36cc0ba560a2"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Options"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d21a3ee-40a0-4a9a-afa3-52b3cf13303e"",
                    ""path"": ""<XInputController>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Options"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2de62cf-dd0d-4ddb-9314-b1612d9e4190"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sound1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""767b04fa-dcc4-4b4e-9c41-9e426b732c17"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sound1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56a26b69-16c9-49bc-8571-e304f699b843"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sound2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0698d3bb-467d-4323-80ee-5278313ffa03"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sound2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef1433a0-ad71-407a-b11b-4b68913755bf"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sound3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aaedee5c-0a99-4fdd-841a-afabf111f144"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sound3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""daf6cf2b-385a-4a2a-bfd0-f6fa9b78312c"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sound4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a712a070-1419-4eb3-bec8-ef236d7e878d"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sound4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b8bd4e98-163a-4d6b-8624-4fce0eed9051"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sound5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""129c74ee-ebbd-4ade-8450-df6b523e798c"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sound6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""575a6fc4-94ce-4c05-9d15-8e7d99d19442"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Diary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85c9621b-8824-4c28-b9d1-5551274d67a6"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Diary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a375a217-82f8-4c35-a065-a4f16506843a"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c93e197d-fbbe-4101-b5eb-7691ab5f05f3"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""518fc0fd-5c2b-4f78-a9d1-86209998bfef"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortCut1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""df239d2a-f765-4c4a-a5d4-aa25378097b5"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortCut1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""a87578f6-6943-41b5-94c2-d5616a9c273e"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortCut1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""624f6dc8-a8a4-4583-a972-3a32a312f6c1"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortCut2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""2d580d6c-1bbc-4e81-8fa7-6481397f9415"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortCut2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""247c3a8b-51db-41e9-be23-76c71a8096c7"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortCut2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""463fe064-7a3d-4530-bb0f-5a71593e5d91"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortCut3"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""c783ca62-05b2-40a3-92fd-392e72917bc2"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortCut3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""23bb704b-bcb9-48a1-a780-0f3a18e1665a"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortCut3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""20f98a4b-52a2-45d5-9ce3-ac76409810f4"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortCut4"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""2c3df7d9-a2e2-4da8-bacd-3824fe9600f0"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortCut4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""e9b962eb-faf7-4f40-8b7c-879e19e7a960"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortCut4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""f07cfa50-fb1b-4495-aa0b-1bdaf69007ec"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortCut5"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""70ab45ed-1de6-4442-a6aa-ec8ab6dc10e9"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortCut5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""5abe818e-7765-43f9-bcf3-3e1a0c2eb1e7"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortCut5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_Interact = m_Player.FindAction("Interact", throwIfNotFound: true);
        m_Player_Sequence = m_Player.FindAction("Sequence", throwIfNotFound: true);
        m_Player_Sphere = m_Player.FindAction("Sphere", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_TakeSound = m_Player.FindAction("TakeSound", throwIfNotFound: true);
        m_Player_Options = m_Player.FindAction("Options", throwIfNotFound: true);
        m_Player_Sound1 = m_Player.FindAction("Sound1", throwIfNotFound: true);
        m_Player_Sound2 = m_Player.FindAction("Sound2", throwIfNotFound: true);
        m_Player_Sound3 = m_Player.FindAction("Sound3", throwIfNotFound: true);
        m_Player_Sound4 = m_Player.FindAction("Sound4", throwIfNotFound: true);
        m_Player_Sound5 = m_Player.FindAction("Sound5", throwIfNotFound: true);
        m_Player_Sound6 = m_Player.FindAction("Sound6", throwIfNotFound: true);
        m_Player_Diary = m_Player.FindAction("Diary", throwIfNotFound: true);
        m_Player_Reset = m_Player.FindAction("Reset", throwIfNotFound: true);
        m_Player_ShortCut1 = m_Player.FindAction("ShortCut1", throwIfNotFound: true);
        m_Player_ShortCut2 = m_Player.FindAction("ShortCut2", throwIfNotFound: true);
        m_Player_ShortCut3 = m_Player.FindAction("ShortCut3", throwIfNotFound: true);
        m_Player_ShortCut4 = m_Player.FindAction("ShortCut4", throwIfNotFound: true);
        m_Player_ShortCut5 = m_Player.FindAction("ShortCut5", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_Interact;
    private readonly InputAction m_Player_Sequence;
    private readonly InputAction m_Player_Sphere;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_TakeSound;
    private readonly InputAction m_Player_Options;
    private readonly InputAction m_Player_Sound1;
    private readonly InputAction m_Player_Sound2;
    private readonly InputAction m_Player_Sound3;
    private readonly InputAction m_Player_Sound4;
    private readonly InputAction m_Player_Sound5;
    private readonly InputAction m_Player_Sound6;
    private readonly InputAction m_Player_Diary;
    private readonly InputAction m_Player_Reset;
    private readonly InputAction m_Player_ShortCut1;
    private readonly InputAction m_Player_ShortCut2;
    private readonly InputAction m_Player_ShortCut3;
    private readonly InputAction m_Player_ShortCut4;
    private readonly InputAction m_Player_ShortCut5;
    public struct PlayerActions
    {
        private @PlayerMap m_Wrapper;
        public PlayerActions(@PlayerMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @Interact => m_Wrapper.m_Player_Interact;
        public InputAction @Sequence => m_Wrapper.m_Player_Sequence;
        public InputAction @Sphere => m_Wrapper.m_Player_Sphere;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @TakeSound => m_Wrapper.m_Player_TakeSound;
        public InputAction @Options => m_Wrapper.m_Player_Options;
        public InputAction @Sound1 => m_Wrapper.m_Player_Sound1;
        public InputAction @Sound2 => m_Wrapper.m_Player_Sound2;
        public InputAction @Sound3 => m_Wrapper.m_Player_Sound3;
        public InputAction @Sound4 => m_Wrapper.m_Player_Sound4;
        public InputAction @Sound5 => m_Wrapper.m_Player_Sound5;
        public InputAction @Sound6 => m_Wrapper.m_Player_Sound6;
        public InputAction @Diary => m_Wrapper.m_Player_Diary;
        public InputAction @Reset => m_Wrapper.m_Player_Reset;
        public InputAction @ShortCut1 => m_Wrapper.m_Player_ShortCut1;
        public InputAction @ShortCut2 => m_Wrapper.m_Player_ShortCut2;
        public InputAction @ShortCut3 => m_Wrapper.m_Player_ShortCut3;
        public InputAction @ShortCut4 => m_Wrapper.m_Player_ShortCut4;
        public InputAction @ShortCut5 => m_Wrapper.m_Player_ShortCut5;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Sequence.started += instance.OnSequence;
            @Sequence.performed += instance.OnSequence;
            @Sequence.canceled += instance.OnSequence;
            @Sphere.started += instance.OnSphere;
            @Sphere.performed += instance.OnSphere;
            @Sphere.canceled += instance.OnSphere;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @TakeSound.started += instance.OnTakeSound;
            @TakeSound.performed += instance.OnTakeSound;
            @TakeSound.canceled += instance.OnTakeSound;
            @Options.started += instance.OnOptions;
            @Options.performed += instance.OnOptions;
            @Options.canceled += instance.OnOptions;
            @Sound1.started += instance.OnSound1;
            @Sound1.performed += instance.OnSound1;
            @Sound1.canceled += instance.OnSound1;
            @Sound2.started += instance.OnSound2;
            @Sound2.performed += instance.OnSound2;
            @Sound2.canceled += instance.OnSound2;
            @Sound3.started += instance.OnSound3;
            @Sound3.performed += instance.OnSound3;
            @Sound3.canceled += instance.OnSound3;
            @Sound4.started += instance.OnSound4;
            @Sound4.performed += instance.OnSound4;
            @Sound4.canceled += instance.OnSound4;
            @Sound5.started += instance.OnSound5;
            @Sound5.performed += instance.OnSound5;
            @Sound5.canceled += instance.OnSound5;
            @Sound6.started += instance.OnSound6;
            @Sound6.performed += instance.OnSound6;
            @Sound6.canceled += instance.OnSound6;
            @Diary.started += instance.OnDiary;
            @Diary.performed += instance.OnDiary;
            @Diary.canceled += instance.OnDiary;
            @Reset.started += instance.OnReset;
            @Reset.performed += instance.OnReset;
            @Reset.canceled += instance.OnReset;
            @ShortCut1.started += instance.OnShortCut1;
            @ShortCut1.performed += instance.OnShortCut1;
            @ShortCut1.canceled += instance.OnShortCut1;
            @ShortCut2.started += instance.OnShortCut2;
            @ShortCut2.performed += instance.OnShortCut2;
            @ShortCut2.canceled += instance.OnShortCut2;
            @ShortCut3.started += instance.OnShortCut3;
            @ShortCut3.performed += instance.OnShortCut3;
            @ShortCut3.canceled += instance.OnShortCut3;
            @ShortCut4.started += instance.OnShortCut4;
            @ShortCut4.performed += instance.OnShortCut4;
            @ShortCut4.canceled += instance.OnShortCut4;
            @ShortCut5.started += instance.OnShortCut5;
            @ShortCut5.performed += instance.OnShortCut5;
            @ShortCut5.canceled += instance.OnShortCut5;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Sequence.started -= instance.OnSequence;
            @Sequence.performed -= instance.OnSequence;
            @Sequence.canceled -= instance.OnSequence;
            @Sphere.started -= instance.OnSphere;
            @Sphere.performed -= instance.OnSphere;
            @Sphere.canceled -= instance.OnSphere;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @TakeSound.started -= instance.OnTakeSound;
            @TakeSound.performed -= instance.OnTakeSound;
            @TakeSound.canceled -= instance.OnTakeSound;
            @Options.started -= instance.OnOptions;
            @Options.performed -= instance.OnOptions;
            @Options.canceled -= instance.OnOptions;
            @Sound1.started -= instance.OnSound1;
            @Sound1.performed -= instance.OnSound1;
            @Sound1.canceled -= instance.OnSound1;
            @Sound2.started -= instance.OnSound2;
            @Sound2.performed -= instance.OnSound2;
            @Sound2.canceled -= instance.OnSound2;
            @Sound3.started -= instance.OnSound3;
            @Sound3.performed -= instance.OnSound3;
            @Sound3.canceled -= instance.OnSound3;
            @Sound4.started -= instance.OnSound4;
            @Sound4.performed -= instance.OnSound4;
            @Sound4.canceled -= instance.OnSound4;
            @Sound5.started -= instance.OnSound5;
            @Sound5.performed -= instance.OnSound5;
            @Sound5.canceled -= instance.OnSound5;
            @Sound6.started -= instance.OnSound6;
            @Sound6.performed -= instance.OnSound6;
            @Sound6.canceled -= instance.OnSound6;
            @Diary.started -= instance.OnDiary;
            @Diary.performed -= instance.OnDiary;
            @Diary.canceled -= instance.OnDiary;
            @Reset.started -= instance.OnReset;
            @Reset.performed -= instance.OnReset;
            @Reset.canceled -= instance.OnReset;
            @ShortCut1.started -= instance.OnShortCut1;
            @ShortCut1.performed -= instance.OnShortCut1;
            @ShortCut1.canceled -= instance.OnShortCut1;
            @ShortCut2.started -= instance.OnShortCut2;
            @ShortCut2.performed -= instance.OnShortCut2;
            @ShortCut2.canceled -= instance.OnShortCut2;
            @ShortCut3.started -= instance.OnShortCut3;
            @ShortCut3.performed -= instance.OnShortCut3;
            @ShortCut3.canceled -= instance.OnShortCut3;
            @ShortCut4.started -= instance.OnShortCut4;
            @ShortCut4.performed -= instance.OnShortCut4;
            @ShortCut4.canceled -= instance.OnShortCut4;
            @ShortCut5.started -= instance.OnShortCut5;
            @ShortCut5.performed -= instance.OnShortCut5;
            @ShortCut5.canceled -= instance.OnShortCut5;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnSequence(InputAction.CallbackContext context);
        void OnSphere(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnTakeSound(InputAction.CallbackContext context);
        void OnOptions(InputAction.CallbackContext context);
        void OnSound1(InputAction.CallbackContext context);
        void OnSound2(InputAction.CallbackContext context);
        void OnSound3(InputAction.CallbackContext context);
        void OnSound4(InputAction.CallbackContext context);
        void OnSound5(InputAction.CallbackContext context);
        void OnSound6(InputAction.CallbackContext context);
        void OnDiary(InputAction.CallbackContext context);
        void OnReset(InputAction.CallbackContext context);
        void OnShortCut1(InputAction.CallbackContext context);
        void OnShortCut2(InputAction.CallbackContext context);
        void OnShortCut3(InputAction.CallbackContext context);
        void OnShortCut4(InputAction.CallbackContext context);
        void OnShortCut5(InputAction.CallbackContext context);
    }
}
